Repository cs169/fa23-chips-10.5-23, pull requests merged in 2023-12, with the labels that each got.

#46 Fix oauth problem client id not found/13
  config/credentials.yml.enc
  config/initializers/omniauth.rb
Labels: bug

#47 Add deploy workflow/41
  .github/workflows/deploy.yml
Labels: iter0, 1point

#63 Add view for article rating/61
  app/controllers/my_news_items_controller.rb
  app/views/my_news_items/search.html.erb
  config/locales/en.yml
  config/routes.rb
  spec/controller/my_news_items_controller_spec.rb
Labels: 1point

#67 Fix uncaught error when invalid address is given
  app/controllers/search_controller.rb
  app/services/representatives_service.rb
  config/locales/en.yml
Labels: bug, 0point, iter2

#74 upd news api key
  config/credentials.yml.enc
Labels: 0point
